#%NASL_MIN_LEVEL 80900
##
# (C) Tenable, Inc.
#
# The package checks in this plugin were extracted from
# AlmaLinux Security Advisory ALSA-2023:4634.
##

include('compat.inc');

if (description)
{
  script_id(179832);
  script_version("1.0");
  script_set_attribute(attribute:"plugin_modification_date", value:"2023/08/15");

  script_cve_id("CVE-2023-38497");
  script_xref(name:"ALSA", value:"2023:4634");

  script_name(english:"AlmaLinux 9 : rust (ALSA-2023:4634)");

  script_set_attribute(attribute:"synopsis", value:
"The remote AlmaLinux host is missing a security update.");
  script_set_attribute(attribute:"description", value:
"The remote AlmaLinux 9 host has packages installed that are affected by a vulnerability as referenced in the
ALSA-2023:4634 advisory.

  - Cargo downloads the Rust project's dependencies and compiles the project. Cargo prior to version 0.72.2,
    bundled with Rust prior to version 1.71.1, did not respect the umask when extracting crate archives on
    UNIX-like systems. If the user downloaded a crate containing files writeable by any local user, another
    local user could exploit this to change the source code compiled and executed by the current user. To
    prevent existing cached extractions from being exploitable, the Cargo binary version 0.72.2 included in
    Rust 1.71.1 or later will purge caches generated by older Cargo versions automatically. As a workaround,
    configure one's system to prevent other local users from accessing the Cargo directory, usually located in
    `~/.cargo`. (CVE-2023-38497)

Note that Nessus has not tested for this issue but has instead relied only on the application's self-reported version
number.");
  script_set_attribute(attribute:"see_also", value:"https://errata.almalinux.org/9/ALSA-2023-4634.html");
  script_set_attribute(attribute:"solution", value:
"Update the affected packages.");
  script_set_cvss_base_vector("CVSS2#AV:L/AC:L/Au:S/C:C/I:C/A:C");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2023-38497");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");
  script_cwe_id(276);

  script_set_attribute(attribute:"vuln_publication_date", value:"2023/08/04");
  script_set_attribute(attribute:"patch_publication_date", value:"2023/08/14");
  script_set_attribute(attribute:"plugin_publication_date", value:"2023/08/15");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:cargo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:clippy");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-analysis");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-analyzer");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-debugger-common");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-doc");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-gdb");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-lldb");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-src");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-std-static");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-std-static-wasm32-unknown-unknown");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-std-static-wasm32-wasi");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rust-toolset");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:alma:linux:rustfmt");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::appstream");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::baseos");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::crb");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::highavailability");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::nfv");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::realtime");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::resilientstorage");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::sap");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::sap_hana");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:alma:linux:9::supplementary");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"Alma Linux Local Security Checks");

  script_copyright(english:"This script is Copyright (C) 2023 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/AlmaLinux/release", "Host/AlmaLinux/rpm-list", "Host/cpu");

  exit(0);
}


include('rpm.inc');

if (!get_kb_item('Host/local_checks_enabled')) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
var os_release = get_kb_item('Host/AlmaLinux/release');
if (isnull(os_release) || 'AlmaLinux' >!< os_release) audit(AUDIT_OS_NOT, 'AlmaLinux');
var os_ver = pregmatch(pattern: "AlmaLinux release ([0-9]+(\.[0-9]+)?)", string:os_release);
if (isnull(os_ver)) audit(AUDIT_UNKNOWN_APP_VER, 'AlmaLinux');
os_ver = os_ver[1];
if (! preg(pattern:"^9([^0-9]|$)", string:os_ver)) audit(AUDIT_OS_NOT, 'AlmaLinux 9.x', 'AlmaLinux ' + os_ver);

if (!get_kb_item('Host/AlmaLinux/rpm-list')) audit(AUDIT_PACKAGE_LIST_MISSING);

var cpu = get_kb_item('Host/cpu');
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ('x86_64' >!< cpu && cpu !~ "^i[3-6]86$" && 's390' >!< cpu && 'aarch64' >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, 'AlmaLinux', cpu);

var pkgs = [
    {'reference':'cargo-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'clippy-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-analysis-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-analyzer-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-debugger-common-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-doc-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-gdb-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-lldb-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-src-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-std-static-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-std-static-wasm32-unknown-unknown-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-std-static-wasm32-wasi-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-toolset-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rustfmt-1.66.1-2.el9_2', 'release':'9', 'rpm_spec_vers_cmp':TRUE}
];

var flag = 0;
foreach var package_array ( pkgs ) {
  var reference = NULL;
  var _release = NULL;
  var sp = NULL;
  var _cpu = NULL;
  var el_string = NULL;
  var rpm_spec_vers_cmp = NULL;
  var epoch = NULL;
  var allowmaj = NULL;
  var exists_check = NULL;
  if (!empty_or_null(package_array['reference'])) reference = package_array['reference'];
  if (!empty_or_null(package_array['release'])) _release = 'Alma-' + package_array['release'];
  if (!empty_or_null(package_array['sp'])) sp = package_array['sp'];
  if (!empty_or_null(package_array['cpu'])) _cpu = package_array['cpu'];
  if (!empty_or_null(package_array['el_string'])) el_string = package_array['el_string'];
  if (!empty_or_null(package_array['rpm_spec_vers_cmp'])) rpm_spec_vers_cmp = package_array['rpm_spec_vers_cmp'];
  if (!empty_or_null(package_array['epoch'])) epoch = package_array['epoch'];
  if (!empty_or_null(package_array['allowmaj'])) allowmaj = package_array['allowmaj'];
  if (!empty_or_null(package_array['exists_check'])) exists_check = package_array['exists_check'];
  if (reference && _release && (!exists_check || rpm_exists(release:_release, rpm:exists_check))) {
    if (rpm_check(release:_release, sp:sp, cpu:_cpu, reference:reference, epoch:epoch, el_string:el_string, rpm_spec_vers_cmp:rpm_spec_vers_cmp, allowmaj:allowmaj)) flag++;
  }
}

if (flag)
{
  security_report_v4(
      port       : 0,
      severity   : SECURITY_WARNING,
      extra      : rpm_report_get()
  );
  exit(0);
}
else
{
  var tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, 'cargo / clippy / rust / rust-analysis / rust-analyzer / etc');
}
