#%NASL_MIN_LEVEL 80900
##
# (C) Tenable, Inc.
#
# The package checks in this plugin were extracted from
# the CentOS Stream Build Service.
##

include('compat.inc');

if (description)
{
  script_id(191261);
  script_version("1.1");
  script_set_attribute(attribute:"plugin_modification_date", value:"2024/04/26");

  script_cve_id("CVE-2023-38497");

  script_name(english:"CentOS 9 : rust-1.71.1-1.el9");

  script_set_attribute(attribute:"synopsis", value:
"The remote CentOS host is missing a security update for cargo.");
  script_set_attribute(attribute:"description", value:
"The remote CentOS Linux 9 host has packages installed that are affected by a vulnerability as referenced in the
rust-1.71.1-1.el9 build changelog.

  - Cargo downloads the Rust project's dependencies and compiles the project. Cargo prior to version 0.72.2,
    bundled with Rust prior to version 1.71.1, did not respect the umask when extracting crate archives on
    UNIX-like systems. If the user downloaded a crate containing files writeable by any local user, another
    local user could exploit this to change the source code compiled and executed by the current user. To
    prevent existing cached extractions from being exploitable, the Cargo binary version 0.72.2 included in
    Rust 1.71.1 or later will purge caches generated by older Cargo versions automatically. As a workaround,
    configure one's system to prevent other local users from accessing the Cargo directory, usually located in
    `~/.cargo`. (CVE-2023-38497)

Note that Nessus has not tested for this issue but has instead relied only on the application's self-reported version
number.");
  script_set_attribute(attribute:"see_also", value:"https://kojihub.stream.centos.org/koji/buildinfo?buildID=36433");
  script_set_attribute(attribute:"solution", value:
"Update the CentOS 9 Stream cargo package.");
  script_set_cvss_base_vector("CVSS2#AV:L/AC:L/Au:S/C:C/I:C/A:C");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:H/A:H");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2023-38497");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");

  script_set_attribute(attribute:"vuln_publication_date", value:"2023/08/04");
  script_set_attribute(attribute:"patch_publication_date", value:"2023/08/14");
  script_set_attribute(attribute:"plugin_publication_date", value:"2024/02/29");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"cpe:/a:centos:centos:9");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:cargo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:clippy");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-analyzer");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-debugger-common");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-doc");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-gdb");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-lldb");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-src");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-std-static");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-std-static-wasm32-unknown-unknown");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-std-static-wasm32-wasi");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rust-toolset");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:rustfmt");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"CentOS Local Security Checks");

  script_copyright(english:"This script is Copyright (C) 2024 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/CentOS/release", "Host/CentOS/rpm-list", "Host/cpu");

  exit(0);
}


include('rpm.inc');
include('rhel.inc');

if (!get_kb_item('Host/local_checks_enabled')) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
var os_release = get_kb_item('Host/CentOS/release');
if (isnull(os_release) || 'CentOS' >!< os_release) audit(AUDIT_OS_NOT, 'CentOS');
var os_ver = pregmatch(pattern: "CentOS(?: Stream)?(?: Linux)? release ([0-9]+)", string:os_release);
if (isnull(os_ver)) audit(AUDIT_UNKNOWN_APP_VER, 'CentOS');
os_ver = os_ver[1];
if (!rhel_check_release(operator: 'ge', os_version: os_ver, rhel_version: '9')) audit(AUDIT_OS_NOT, 'CentOS 9.x', 'CentOS ' + os_ver);

if (!get_kb_item('Host/CentOS/rpm-list')) audit(AUDIT_PACKAGE_LIST_MISSING);

var cpu = get_kb_item('Host/cpu');
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ('x86_64' >!< cpu && cpu !~ "^i[3-6]86$" && 's390' >!< cpu && 'aarch64' >!< cpu && 'ppc' >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, 'CentOS', cpu);

var pkgs = [
    {'reference':'cargo-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'clippy-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-analyzer-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-debugger-common-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-doc-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-gdb-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-lldb-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-src-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-std-static-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-std-static-wasm32-unknown-unknown-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-std-static-wasm32-wasi-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rust-toolset-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'rustfmt-1.71.1-1.el9', 'release':'9', 'rpm_spec_vers_cmp':TRUE}
];

var flag = 0;
foreach var package_array ( pkgs ) {
  var reference = NULL;
  var _release = NULL;
  var sp = NULL;
  var _cpu = NULL;
  var el_string = NULL;
  var rpm_spec_vers_cmp = NULL;
  var epoch = NULL;
  var allowmaj = NULL;
  if (!empty_or_null(package_array['reference'])) reference = package_array['reference'];
  if (!empty_or_null(package_array['release'])) _release = 'CentOS-' + package_array['release'];
  if (!empty_or_null(package_array['sp'])) sp = package_array['sp'];
  if (!empty_or_null(package_array['cpu'])) _cpu = package_array['cpu'];
  if (!empty_or_null(package_array['el_string'])) el_string = package_array['el_string'];
  if (!empty_or_null(package_array['rpm_spec_vers_cmp'])) rpm_spec_vers_cmp = package_array['rpm_spec_vers_cmp'];
  if (!empty_or_null(package_array['epoch'])) epoch = package_array['epoch'];
  if (!empty_or_null(package_array['allowmaj'])) allowmaj = package_array['allowmaj'];
  if (reference && _release) {
    if (rpm_check(release:_release, sp:sp, cpu:_cpu, reference:reference, epoch:epoch, el_string:el_string, rpm_spec_vers_cmp:rpm_spec_vers_cmp, allowmaj:allowmaj)) flag++;
  }
}

if (flag)
{
  security_report_v4(
      port       : 0,
      severity   : SECURITY_WARNING,
      extra      : rpm_report_get()
  );
  exit(0);
}
else
{
  var tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, 'cargo / clippy / rust / rust-analyzer / rust-debugger-common / etc');
}
