#TRUSTED 3916cde8a266b139b69df219d0becf0f2e6b841b8547d056133170d5f1492d1be21513ab5d52633b1731923ef3239ff9bb0b4884dfbd4b64a420cbcfcf956e5dae9a86e26232836b0711830f5528fd0211ddfea6e20018f251c057d23b35150080cf51707c5d3e4fe66aff14b31d24309aea85127428011568323bfc23d5cc7000868cdeb84df017b16dd12ad2580ef940bcdc2c637ef01d49100cc5d880061c27a0570918406559d72a58885e8ecdcc568e635b69f13205f3d41c27fdfd92050c31ea8cfa26227585cd424f4adfb23ce1976f2de70292942ecf1cc1f6f1d43ad7ffa764d229ffa1226c4cd3bd180ba0fbcb3fbeda93e33458c3b55a0e47b6d042a75c37e51740d5d6f6fafcf7d25a8eda4c1352802d82e2871594dc143f6f4a26c85d31f6e4b02b8767e8e039499da2efce495fcad59c14094501207707d2f6a07bc1a972ee12ec92eae6912bbfd9dd0d730819db245cd7f02b869abfca64136bd37c41b90c6ac83c098f0dd2bd527d759217ea2690f121cd78072e23a52f84de7d58da8b400a0722a529a6cac913f98f611af4aaa6cbe02c804c0e51679c6b7745a3f965eba52308ad9532717822b0f25ce2680f60e52e99acfdb60cf30411fc26193d353dee534d3fb214ae78f8861537f64e3ef468ca76481f0cd8a911a428dc700f81909ba3dd467c61b47ebbd5a34e61fb03393bc16eefa3afd5e90914
#TRUST-RSA-SHA256 2c3fc4921965b4968aa38feaaaa451cfe1ed712dec54667f8b334afae4632c8f861f859f899764a48e93819487ab84cfa71e48f253b0ceb291dd388f3db7b8dbb4489e536eff01779cb37245677cecbe203a8907c0fea91f172f7bcf2567c0df328fff089c7a634c7a6ce0d4e9fc3e93f6df04bda2f29f1254cfaca004f7407ad74810de0e4013f203bacdbce413039a178523dce58be5f06101edeeea3e3ff24f05511a53d4b652fc4d9ca7a812e286aba3449d0a5ba88be3cd4ec23c8378f5a13e2c954a6c01fbf4342c0938413b96b04c0b50136d75a8828cb181eecf522fde2aef4f352d3e6cfe468f97ead69d30ea0a23dbb6b3eab08efdfda222d9e91ed7243929bbf5d1ffa91e8589f204eb42bc59e2824d33817b84b01debb9fe6d3bc8ec2e0be3c4292e96c69381592ccf081659e210f95617c3c438a7f78339c83f5fa07485496c389b99619cf3dd664b971d40cabfb1ac2b20c273c2800ea77e00c7524e58813808ca4d1bf884edecb8f33713a1ed18ec5ae89fa05600b4409050f97677d6f09059a5147116b69e5a6277774f14f37712a77146ffd223c00fa0f569f341b36c5e3a468060a291e85ced85171ffebdc279d3459317641fb784f4a2bc4143428041c4dc78f3e1de6eb7dbc2eb49a2e4e404d3f9ed4897c092612a09073811df42a5eb1e576275a448ae586095b97f3b8bad4ca6f3657789614a2996
#%NASL_MIN_LEVEL 80900
##
# (C) Tenable, Inc.
##

include('compat.inc');

if (description)
{
  script_id(235488);
  script_version("1.2");
  script_set_attribute(attribute:"plugin_modification_date", value:"2025/05/09");

  script_cve_id("CVE-2025-20155");
  script_xref(name:"CISCO-BUG-ID", value:"CSCwj60286");
  script_xref(name:"CISCO-SA", value:"cisco-sa-bootstrap-KfgxYgdh");
  script_xref(name:"IAVA", value:"2025-A-0318");

  script_name(english:"Cisco IOS XE Software Bootstrap Arbitrary File Write (cisco-sa-bootstrap-KfgxYgdh)");

  script_set_attribute(attribute:"synopsis", value:
"The remote device is missing a vendor-supplied security patch");
  script_set_attribute(attribute:"description", value:
"According to its self-reported version, Cisco IOS-XE Software is affected by a vulnerability.

  - A vulnerability in the bootstrap loading of Cisco IOS XE Software could allow an authenticated, local
    attacker to write arbitrary files to an affected system. This vulnerability is due to insufficient input
    validation of the bootstrap file that is read by the system software when a device is first deployed in
    SD-WAN mode or when an administrator configures SD-Routing on the device. An attacker could exploit this
    vulnerability by modifying a bootstrap file generated by Cisco Catalyst SD-WAN Manager, loading it into
    the device flash, and then either reloading the device in a green field deployment in SD-WAN mode or
    configuring the device with SD-Routing. A successful exploit could allow the attacker to perform arbitrary
    file writes to the underlying operating system. (CVE-2025-20155)

Please see the included Cisco BIDs and Cisco Security Advisory for more information.");
  # https://sec.cloudapps.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-bootstrap-KfgxYgdh
  script_set_attribute(attribute:"see_also", value:"http://www.nessus.org/u?dd848aa4");
  # https://sec.cloudapps.cisco.com/security/center/viewErp.x?alertId=ERP-75279
  script_set_attribute(attribute:"see_also", value:"http://www.nessus.org/u?564dd2a1");
  script_set_attribute(attribute:"see_also", value:"https://bst.cloudapps.cisco.com/bugsearch/bug/CSCwj60286");
  script_set_attribute(attribute:"solution", value:
"Upgrade to the relevant fixed version referenced in Cisco bug ID CSCwj60286");
  script_set_cvss_base_vector("CVSS2#AV:L/AC:L/Au:M/C:C/I:C/A:N");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:N");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2025-20155");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");
  script_cwe_id(1287);

  script_set_attribute(attribute:"vuln_publication_date", value:"2025/05/07");
  script_set_attribute(attribute:"patch_publication_date", value:"2025/05/07");
  script_set_attribute(attribute:"plugin_publication_date", value:"2025/05/07");

  script_set_attribute(attribute:"plugin_type", value:"combined");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:cisco:ios_xe");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_set_attribute(attribute:"stig_severity", value:"I");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"CISCO");

  script_copyright(english:"This script is Copyright (C) 2025 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("cisco_ios_xe_version.nasl");
  script_require_keys("Host/Cisco/IOS-XE/Version");

  exit(0);
}

include('ccf.inc');

var product_info = cisco::get_product_info(name:'Cisco IOS XE Software');

var version_list=make_list(
  '17.9.4',
  '17.9.4a',
  '17.9.5',
  '17.9.5a',
  '17.9.5b',
  '17.9.5c',
  '17.9.5d',
  '17.9.5e',
  '17.9.5f',
  '17.9.6',
  '17.9.6a',
  '17.9.6b',
  '17.11.99SW',
  '17.12.1',
  '17.12.1a',
  '17.12.1w',
  '17.12.1x',
  '17.12.1y',
  '17.12.1z',
  '17.12.1z1',
  '17.12.2',
  '17.12.2a',
  '17.12.3',
  '17.12.3a',
  '17.12.4',
  '17.12.4a',
  '17.12.4b',
  '17.13.1',
  '17.13.1a',
  '17.14.1',
  '17.14.1a'
);

var reporting = make_array(
  'port'          , product_info['port'],
  'severity'      , SECURITY_WARNING,
  'version'       , product_info['version'],
  'bug_id'        , 'CSCwj60286',
  'disable_caveat', TRUE
);

cisco::check_and_report(
  product_info:product_info,
  reporting:reporting,
  vuln_versions:version_list
);
