#%NASL_MIN_LEVEL 80900
#
# (C) Tenable, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from Debian Security Advisory dla-3149. The text
# itself is copyright (C) Software in the Public Interest, Inc.
#

include('compat.inc');

if (description)
{
  script_id(166069);
  script_version("1.3");
  script_set_attribute(attribute:"plugin_modification_date", value:"2025/01/22");

  script_cve_id("CVE-2019-5477", "CVE-2020-26247", "CVE-2022-24836");

  script_name(english:"Debian dla-3149 : ruby-nokogiri - security update");

  script_set_attribute(attribute:"synopsis", value:
"The remote Debian host is missing one or more security-related updates.");
  script_set_attribute(attribute:"description", value:
"The remote Debian 10 host has a package installed that is affected by multiple vulnerabilities as referenced in the
dla-3149 advisory.

    - -------------------------------------------------------------------------
    Debian LTS Advisory DLA-3149-1                debian-lts@lists.debian.org
    https://www.debian.org/lts/security/                      Sylvain Beucler
    October 12, 2022                              https://wiki.debian.org/LTS
    - -------------------------------------------------------------------------

    Package        : ruby-nokogiri
    Version        : 1.10.0+dfsg1-2+deb10u1
    CVE ID         : CVE-2019-5477 CVE-2020-26247 CVE-2022-24836
    Debian Bug     : 934802 978967 1009787

    Multiple vulnerabilities were discovered in Nokogiri, an
    HTML/XML/SAX/Reader parser for the Ruby programming language, leading
    to command injection, XML external entity injection (XXE), and
    denial-of-service (DoS).

    CVE-2019-5477

        A command injection vulnerability allows commands to be executed
        in a subprocess via Ruby's `Kernel.open` method. Processes are
        vulnerable only if the undocumented method
        `Nokogiri::CSS::Tokenizer#load_file` is being called with unsafe
        user input as the filename. This vulnerability appears in code
        generated by the Rexical gem versions v1.0.6 and earlier. Rexical
        is used by Nokogiri to generate lexical scanner code for parsing
        CSS queries.

    CVE-2020-26247

        XXE vulnerability: XML Schemas parsed by Nokogiri::XML::Schema are
        trusted by default, allowing external resources to be accessed
        over the network, potentially enabling XXE or SSRF attacks. This
        behavior is counter to the security policy followed by Nokogiri
        maintainers, which is to treat all input as untrusted by default
        whenever possible.

    CVE-2022-24836

        Nokogiri contains an inefficient regular expression that is
        susceptible to excessive backtracking when attempting to detect
        encoding in HTML documents.

    For Debian 10 buster, these problems have been fixed in version
    1.10.0+dfsg1-2+deb10u1.

    We recommend that you upgrade your ruby-nokogiri packages.

    For the detailed security status of ruby-nokogiri please refer to
    its security tracker page at:
    https://security-tracker.debian.org/tracker/ruby-nokogiri

    Further information about Debian LTS security advisories, how to apply
    these updates to your system and frequently asked questions can be
    found at: https://wiki.debian.org/LTS

Tenable has extracted the preceding description block directly from the Debian security advisory.

Note that Nessus has not tested for these issues but has instead relied only on the application's self-reported version
number.");
  # https://security-tracker.debian.org/tracker/source-package/ruby-nokogiri
  script_set_attribute(attribute:"see_also", value:"http://www.nessus.org/u?a4325c6e");
  script_set_attribute(attribute:"see_also", value:"https://security-tracker.debian.org/tracker/CVE-2019-5477");
  script_set_attribute(attribute:"see_also", value:"https://security-tracker.debian.org/tracker/CVE-2020-26247");
  script_set_attribute(attribute:"see_also", value:"https://security-tracker.debian.org/tracker/CVE-2022-24836");
  script_set_attribute(attribute:"see_also", value:"https://packages.debian.org/source/buster/ruby-nokogiri");
  script_set_attribute(attribute:"solution", value:
"Upgrade the ruby-nokogiri packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:P/I:P/A:P");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2019-5477");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");

  script_set_attribute(attribute:"vuln_publication_date", value:"2019/08/16");
  script_set_attribute(attribute:"patch_publication_date", value:"2022/10/12");
  script_set_attribute(attribute:"plugin_publication_date", value:"2022/10/12");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:debian:debian_linux:ruby-nokogiri");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:debian:debian_linux:10.0");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"Debian Local Security Checks");

  script_copyright(english:"This script is Copyright (C) 2022-2025 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/Debian/release", "Host/Debian/dpkg-l");

  exit(0);
}

include('debian_package.inc');

if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
if (!get_kb_item("Host/Debian/dpkg-l")) audit(AUDIT_PACKAGE_LIST_MISSING);

var debian_release = get_kb_item('Host/Debian/release');
if ( isnull(debian_release) ) audit(AUDIT_OS_NOT, 'Debian');
debian_release = chomp(debian_release);
if (! preg(pattern:"^(10)\.[0-9]+", string:debian_release)) audit(AUDIT_OS_NOT, 'Debian 10.0', 'Debian ' + debian_release);
var cpu = get_kb_item('Host/cpu');
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ('x86_64' >!< cpu && cpu !~ "^i[3-6]86$" && 'aarch64' >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, 'Debian', cpu);

var pkgs = [
    {'release': '10.0', 'prefix': 'ruby-nokogiri', 'reference': '1.10.0+dfsg1-2+deb10u1'}
];

var flag = 0;
foreach package_array ( pkgs ) {
  var _release = NULL;
  var prefix = NULL;
  var reference = NULL;
  if (!empty_or_null(package_array['release'])) _release = package_array['release'];
  if (!empty_or_null(package_array['prefix'])) prefix = package_array['prefix'];
  if (!empty_or_null(package_array['reference'])) reference = package_array['reference'];
  if (_release && prefix && reference) {
    if (deb_check(release:_release, prefix:prefix, reference:reference)) flag++;
  }
}

if (flag)
{
  security_report_v4(
    port       : 0,
    severity   : SECURITY_HOLE,
    extra      : deb_report_get()
  );
  exit(0);
}
else
{
  var tested = deb_pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, 'ruby-nokogiri');
}
