###                                                                                                                                      
# (C) Tenable, Inc.
#
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable, Inc.
#
# @NOGPL@
#
# jenkins_plugin_mappings.inc
#
# Revision: 1.5
#
# This .inc file is no longer used due to changes in vcf_extras.inc and jenkins_detect.inc
###

# Variable present for compilation purposes
var jenkins_plugin_mappings = 1;
