#
# (C) Tenable Network Security, Inc.
#
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable Network Security, Inc.
#
# @NOGPL@
#
# joomla_extension_list.inc
#
# Revision: 1.1


global_var JOOMLA_EXTENSIONS = [
  { "pretty_name": "JCK Suite", "extension": "jcksuite" },
  { "pretty_name": "ARK Editor", "extension": "arkeditor" },
  { "pretty_name": "ChronoForms", "extension": "chronoforms6" }
];

