##
# (C) Tenable Network Security, Inc.
#
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable Network Security Inc.
#
# @NOGPL@
#
# Revision: 1.3
# This file has been replaced by includes/lcx_globals.static for the transition to pre-compiled plugins#
##

#pragma static(include)
include("lcx_globals.static");
#pragma static(include:false)

