#%NASL_MIN_LEVEL 70300
#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from Red Hat Security Advisory RHSA-2012:0813 and 
# Oracle Linux Security Advisory ELSA-2012-0813 respectively.
#

include('deprecated_nasl_level.inc');
include('compat.inc');

if (description)
{
  script_id(68552);
  script_version("1.8");
  script_set_attribute(attribute:"plugin_modification_date", value:"2024/10/22");

  script_cve_id("CVE-2012-0833");
  script_bugtraq_id(52044);
  script_xref(name:"RHSA", value:"2012:0813");

  script_name(english:"Oracle Linux 6 : 389-ds-base (ELSA-2012-0813)");

  script_set_attribute(attribute:"synopsis", value:
"The remote Oracle Linux host is missing a security update.");
  script_set_attribute(attribute:"description", value:
"The remote Oracle Linux 6 host has packages installed that are affected by a vulnerability as referenced in the
ELSA-2012-0813 advisory.

    [1.2.10.2-15]
    - Resolves: Bug 824014 - DS Shuts down intermittently

    [1.2.10.2-14]
    - Resolves: Bug 819643 - Database RUV could mismatch the one in changelog under the stress
    -- patch 0015 fixes a small memleak in previous patch

    [1.2.10.2-13]
    - Resolves: Bug 822700 - Bad DNs in ACIs can segfault ns-slapd

    [1.2.10.2-12]
    - Resolves: Bug 819643 - Database RUV could mismatch the one in changelog under the stress
    - Resolves: Bug 821542 - letters in object's cn get converted to lowercase when renaming object

    [1.2.10.2-11]
    - Resolves: Bug 819643 - Database RUV could mismatch the one in changelog under the stress
    - 1.2.10.2-10 was built from the private branch

    [1.2.10.2-10]
    - Resolves: Bug 819643 - Database RUV could mismatch the one in changelog under the stress

    [1.2.10.2-9]
    - Resolves: Bug 815991 - crash in ldap_initialize with multiple threads
    -  previous fix was still crashing in ldclt

    [1.2.10.2-8]
    - Resolves: Bug 815991 - crash in ldap_initialize with multiple threads

    [1.2.10.2-7]
    - Resolves: Bug 813964 - IPA dirsvr seg-fault during system longevity test

    [1.2.10.2-6]
    - Resolves: Bug 811291 - [abrt] 389-ds-base-1.2.10.4-2.fc16: index_range_read_ext: Process /usr/sbin/ns-
    slapd was killed by signal 11 (SIGSEGV)
    - typo in previous patch

    [1.2.10.2-5]
    - Resolves: Bug 811291 - [abrt] 389-ds-base-1.2.10.4-2.fc16: index_range_read_ext: Process /usr/sbin/ns-
    slapd was killed by signal 11 (SIGSEGV)

    [1.2.10.2-4]
    - Resolves: Bug 803930 - ipa not starting after upgade because of missing data
    - get rid of posttrans - move update code to post

    [1.2.10.2-3]
    - Resolves: Bug 800215 - Certain CMP operations hang or cause ns-slapd to crash

    [1.2.10.2-2]
    - Resolves: Bug 800215 - Certain CMP operations hang or cause ns-slapd to crash
    - Resolves: Bug 800217 - fix valgrind reported issues

    [1.2.10.2-1]
    - Resolves: Bug 766989 - Rebase 389-ds-base to 1.2.10
    - Resolves: Bug 796770 - crash when replicating orphaned tombstone entry

    [1.2.10.1-1]
    - Resolves: Bug 766989 - Rebase 389-ds-base to 1.2.10
    - Resolves: Bug 790491 - 389 DS Segfaults during replica install in FreeIPA

    [1.2.10.0-1]
    - Resolves: Bug 766989 - Rebase 389-ds-base to 1.2.10

    [1.2.10-0.11.rc2]
    - Resolves: Bug 766989 - Rebase 389-ds-base to 1.2.10

    [1.2.9.16-1]
    - Bug 759301 - Incorrect entryUSN index under high load in replicated environment
    - Bug 743979 - Add slapi_rwlock API and use POSIX rwlocks
    - WARNING - patches 0030 and 0031 remove and add back the file configure
    - this is necessary because the merge commit to rebase RHEL-6 to 1.2.9.6
    - seriously messed up configure - so in order to add the patch for 743979
    - which also touched configure, the file had to be removed and added back
    - also note that the commit for the RHEL-6 branch to remove configure does
    - not work - the way patch works, it has to match every line exactly in
    - order to remove the file, and because the merge commit messed things
    - up, it doesn't work
    - So, DO NOT TOUCH 0030-remove-configure-to-get-rid-of-merge-conflict.patch
    - BECAUSE IT IS HAND CRAFTED and not generated by git format-patch
    - if you must regenerate this file,
    - git format-patch ...args... to generate a file in patch format
    - remove all of the patch matches (all the lines beginning with -)
    - get the 1.2.9.6 version of configure from the source tarball
    - wc -l configure to get the number of lines in the file
    - sed 's/^/-/' configure >> thefile.patch
    - edit thefile.patch to have the right number of lines and have the
    - patch commands in the correct place
    - PROFIT!!!

    [1.2.9.15-1]
    - Bug 752577 - crash when simple paged fails to send entry to client
    - Bug 757897 - rhds81 modrn operation and 100% cpu use in replication
    - Bug 757898 - Fix Coverity (11104) Resource leak: ids_sasl_user_to_entry (slapd/saslbind.c)

Tenable has extracted the preceding description block directly from the Oracle Linux security advisory.

Note that Nessus has not tested for this issue but has instead relied only on the application's self-reported version
number.");
  script_set_attribute(attribute:"see_also", value:"https://linux.oracle.com/errata/ELSA-2012-0813.html");
  script_set_attribute(attribute:"solution", value:
"Update the affected 389-ds-base, 389-ds-base-devel and / or 389-ds-base-libs packages.");
  script_set_cvss_base_vector("CVSS2#AV:A/AC:M/Au:S/C:N/I:N/A:P");
  script_set_cvss_temporal_vector("CVSS2#E:POC/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:P/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2012-0833");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");

  script_set_attribute(attribute:"vuln_publication_date", value:"2012/07/03");
  script_set_attribute(attribute:"patch_publication_date", value:"2012/07/02");
  script_set_attribute(attribute:"plugin_publication_date", value:"2013/07/12");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:oracle:linux:389-ds-base");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:oracle:linux:389-ds-base-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:oracle:linux:389-ds-base-libs");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:oracle:linux:6");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"Oracle Linux Local Security Checks");

  script_copyright(english:"This script is Copyright (C) 2013-2024 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/OracleLinux", "Host/RedHat/release", "Host/RedHat/rpm-list");

  exit(0);
}


include('rpm.inc');

if (!get_kb_item('Host/local_checks_enabled')) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
if (!get_kb_item('Host/OracleLinux')) audit(AUDIT_OS_NOT, 'Oracle Linux');
var os_release = get_kb_item("Host/RedHat/release");
if (isnull(os_release) || !pregmatch(pattern: "Oracle (?:Linux Server|Enterprise Linux)", string:os_release)) audit(AUDIT_OS_NOT, 'Oracle Linux');
var os_ver = pregmatch(pattern: "Oracle (?:Linux Server|Enterprise Linux) .*release ([0-9]+(\.[0-9]+)?)", string:os_release);
if (isnull(os_ver)) audit(AUDIT_UNKNOWN_APP_VER, 'Oracle Linux');
os_ver = os_ver[1];
if (! preg(pattern:"^6([^0-9]|$)", string:os_ver)) audit(AUDIT_OS_NOT, 'Oracle Linux 6', 'Oracle Linux ' + os_ver);

if (!get_kb_item('Host/RedHat/rpm-list')) audit(AUDIT_PACKAGE_LIST_MISSING);

var cpu = get_kb_item('Host/cpu');
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ('x86_64' >!< cpu && cpu !~ "^i[3-6]86$" && 'aarch64' >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, 'Oracle Linux', cpu);

var pkgs = [
    {'reference':'389-ds-base-1.2.10.2-15.el6', 'cpu':'i686', 'release':'6', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'389-ds-base-devel-1.2.10.2-15.el6', 'cpu':'i686', 'release':'6', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'389-ds-base-libs-1.2.10.2-15.el6', 'cpu':'i686', 'release':'6', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'389-ds-base-1.2.10.2-15.el6', 'cpu':'x86_64', 'release':'6', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'389-ds-base-devel-1.2.10.2-15.el6', 'cpu':'x86_64', 'release':'6', 'rpm_spec_vers_cmp':TRUE},
    {'reference':'389-ds-base-libs-1.2.10.2-15.el6', 'cpu':'x86_64', 'release':'6', 'rpm_spec_vers_cmp':TRUE}
];

var flag = 0;
foreach var package_array ( pkgs ) {
  var reference = NULL;
  var _release = NULL;
  var sp = NULL;
  var _cpu = NULL;
  var el_string = NULL;
  var rpm_spec_vers_cmp = NULL;
  var epoch = NULL;
  var allowmaj = NULL;
  var exists_check = NULL;
  if (!empty_or_null(package_array['reference'])) reference = package_array['reference'];
  if (!empty_or_null(package_array['release'])) _release = 'EL' + package_array['release'];
  if (!empty_or_null(package_array['sp'])) sp = package_array['sp'];
  if (!empty_or_null(package_array['cpu'])) _cpu = package_array['cpu'];
  if (!empty_or_null(package_array['el_string'])) el_string = package_array['el_string'];
  if (!empty_or_null(package_array['rpm_spec_vers_cmp'])) rpm_spec_vers_cmp = package_array['rpm_spec_vers_cmp'];
  if (!empty_or_null(package_array['epoch'])) epoch = package_array['epoch'];
  if (!empty_or_null(package_array['allowmaj'])) allowmaj = package_array['allowmaj'];
  if (!empty_or_null(package_array['exists_check'])) exists_check = package_array['exists_check'];
  if (reference && _release) {
    if (exists_check) {
        if (rpm_exists(release:_release, rpm:exists_check) && rpm_check(release:_release, sp:sp, cpu:cpu, reference:reference, epoch:epoch, el_string:el_string, rpm_spec_vers_cmp:rpm_spec_vers_cmp, allowmaj:allowmaj)) flag++;
    } else {
        if (rpm_check(release:_release, sp:sp, cpu:_cpu, reference:reference, epoch:epoch, el_string:el_string, rpm_spec_vers_cmp:rpm_spec_vers_cmp, allowmaj:allowmaj)) flag++;
    }
  }
}

if (flag)
{
  security_report_v4(
      port       : 0,
      severity   : SECURITY_NOTE,
      extra      : rpm_report_get()
  );
  exit(0);
}
else
{
  var tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, '389-ds-base / 389-ds-base-devel / 389-ds-base-libs');
}
