#------------------------------------------------------------------------------
#
# (C) Tenable Network Security, Inc.
#
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable Network Security, Inc.
#
# @NOGPL@
#
# smb_glue.inc
# Revision: 1.30
#

# This file has been replaced by includes/smb_glue.static for the transition to pre-compiled plugins
#pragma static(include)
include("smb_glue.static");
#pragma static(include:false)
