# -*- Fundamental -*-
#
# (C) Tenable Network Security, Inc.
#
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable Network Security, Inc.
#
# @NOGPL@
#
# smb_file_funcs.inc
# Revision: 1.7
#
# 7/18/2019 - Removed contents since as it is this file cannot coexist with
#             pre-compiled plugins since it calls functions that don't exist
#             in the product and is itself never used.

global_var __smb_file_funcs_is_deprecated=1;

