###
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable Network Security Inc.
#
# (C) Tenable Network Security, Inc.
#
#
#
# Revision 1.0

# This file has been replaced by includes/ssh_lib_firepower_shell_handlers.static for the transition to pre-compiled plugins
include("ssh_lib.inc");
#pragma static(include)
include("ssh_lib_firepower_shell_handlers.static");
#pragma static(include:false)
