#%NASL_MIN_LEVEL 80900
##
# (C) Tenable, Inc.
#
# The package checks in this plugin were extracted from
# SUSE update advisory SUSE-SU-2025:0033-1. The text itself
# is copyright (C) SUSE.
##

include('compat.inc');

if (description)
{
  script_id(213596);
  script_version("1.3");
  script_set_attribute(attribute:"plugin_modification_date", value:"2025/03/13");

  script_cve_id(
    "CVE-2024-50379",
    "CVE-2024-52317",
    "CVE-2024-54677",
    "CVE-2024-56337"
  );
  script_xref(name:"IAVA", value:"2024-A-0754-S");
  script_xref(name:"SuSE", value:"SUSE-SU-2025:0033-1");
  script_xref(name:"IAVA", value:"2024-A-0822-S");

  script_name(english:"SUSE SLES15 / openSUSE 15 Security Update : tomcat10 (SUSE-SU-2025:0033-1)");

  script_set_attribute(attribute:"synopsis", value:
"The remote SUSE host is missing one or more security updates.");
  script_set_attribute(attribute:"description", value:
"The remote SUSE Linux SLES15 / SLES_SAP15 / openSUSE 15 host has packages installed that are affected by multiple
vulnerabilities as referenced in the SUSE-SU-2025:0033-1 advisory.

    Update to Tomcat 10.1.34

    - Fixed CVEs:
      - CVE-2024-54677: DoS in examples web application (bsc#1234664)
      - CVE-2024-50379: RCE due to TOCTOU issue in JSP compilation (bsc#1234663)
      - CVE-2024-52317: Request/response mix-up with HTTP/2 (bsc#1233435)
      - CVE-2024-56337: RCE due to TOCTOU issue in JSP compilation - mitigation was incomplete
    - Catalina
      - Add: Add option to serve resources from subpath only with WebDAV Servlet
        like with DefaultServlet. (michaelo)
      - Fix: Add special handling for the protocols attribute of SSLHostConfig in
        storeconfig. (remm)
      - Fix: 69442: Fix case sensitive check on content-type when parsing request
        parameters. (remm)
      - Code: Refactor duplicate code for extracting media type and subtype from
        content-type into a single method. (markt)
      - Fix: Compatibility of generated embedded code with components where
        constructors or property related methods throw a checked exception. (remm)
      - Fix: The previous fix for inconsistent resource metadata during concurrent
        reads and writes was incomplete. (markt)
      - Fix: #780: Fix content-range header length. Submitted by Chenjp. (remm)
      - Fix: 69444: Ensure that the jakarta.servlet.error.message request
        attribute is set when an application defined error page is called. (markt)
      - Fix: Avoid quotes for numeric values in the JSON generated by the status
        servlet. (remm)
      - Add: Add strong ETag support for the WebDAV and default servlet, which can
        be enabled by using the useStrongETags init parameter with a value set to
        true. The ETag generated will be a SHA-1 checksum of the resource content.
        (remm)
      - Fix: Use client locale for directory listings. (remm)
      - Fix: 69439: Improve the handling of multiple Cache-Control headers in the
        ExpiresFilter. Based on pull request #777 by Chenjp. (markt)
      - Fix: 69447: Update the support for caching classes the web application
        class loader cannot find to take account of classes loaded from external
        repositories. Prior to this fix, these classes could be incorrectly marked
        as not found. (markt)
      - Fix: 69466: Rework handling of HEAD requests. Headers explicitly set by
        users will not be removed and any header present in a HEAD request will
        also be present in the equivalent GET request. There may be some headers,
        as per RFC 9110, section 9.3.2, that are present in a GET request that are
        not present in the equivalent HEAD request. (markt)
      - Fix: 69471: Log instances of CloseNowException caught by
        ApplicationDispatcher.invoke() at debug level rather than error level as
        they are very likely to have been caused by a client disconnection or
        similar I/O issue. (markt)
      - Add: Add a test case for the fix for 69442. Also refactor references to
        application/x-www-form-urlencoded. Based on pull request #779 by Chenjp.
        (markt)
      - Fix: 69476: Catch possible ISE when trying to report PUT failure in the
        DefaultServlet. (remm)
      - Add: Add support for RateLimit header fields for HTTP (draft) in the
        RateLimitFilter. Based on pull request #775 provided by Chenjp. (markt)
      - Add: #787: Add regression tests for 69478. Pull request provided by Thomas
        Krisch. (markt)
      - Fix: The default servlet now rejects HTTP range requests when two or more
        of the requested ranges overlap. Based on pull request #782 provided by
        Chenjp. (markt)
      + Fix: Enhance Content-Range verification for partial PUT requests handled
        by the default servlet. Provided by Chenjp in pull request #778. (markt)
      + Fix: Harmonize DataSourceStore lookup in the global resources to
        optionally avoid the comp/env prefix which is usually not used there.
        (remm)
      + Fix: As required by RFC 9110, the HTTP Range header will now only be
        processed for GET requests. Based on pull request #790 provided by Chenjp.
        (markt)
      + Fix: Deprecate the useAcceptRanges initialisation parameter for the
        default servlet. It will be removed in Tomcat 12 onwards where it will
        effectively be hard coded to true. (markt)
      + Add: Add DataSource based property storage for the WebdavServlet. (remm)
    - Coyote
      + Fix: Align encodedSolidusHandling with the Servlet specification. If the
        pass-through mode is used, any %25 sequences will now also be passed
        through to avoid errors and/or corruption when the application decodes the
        path. (markt)
    - Jasper
      + Fix: Follow-up to the fix for 69381. Apply the optimisation for method
        lookup performance in expression language to an additional location.
        (markt)
    - Web applications
      + Fix: Documentation. Remove references to the ResourceParams element.
        Support for ResourceParams was removed in Tomcat 5.5.x. (markt)
      + Fix: Documentation. 69477: Correct name of attribute for RemoteIPFilter.
        The attribute is internalProxies rather than allowedInternalProxies. Pull
        request #786 (markt)
      + Fix: Examples. Fix broken links when Servlet Request Info example is
        called via a URL that includes a pathInfo component. (markt)
      + Fix: Examples. Expand the obfuscation of session cookie values in the
        request header example to JSON responses. (markt)
      + Add: Examples. Add the ability to delete session attributes in the servlet
        session example. (markt)
      + Add: Examples. Add a hard coded limit of 10 attributes per session for the
        servlet session example. (markt)
      + Add: Examples. Add the ability to delete session attributes and add a hard
        coded limit of 10 attributes per session for the JSP form authentication
        example. (markt)
      + Add: Examples. Limit the shopping cart example to only allow adding the
        pre-defined items to the cart. (markt)
      + Fix: Examples. Remove JSP calendar example. (markt)
    - Other
      + Fix: 69465: Fix warnings during native image compilation using the Tomcat
        embedded JARs. (markt)
      + Update: Update Tomcat's fork of Commons DBCP to 2.13.0. (markt)
      + Update: Update EasyMock to 5.5.0. (markt)
      + Update: Update Checkstyle to 10.20.2. (markt)
      + Update: Update BND to 7.1.0. (markt)
      + Add: Improvements to French translations. (remm)
      + Add: Improvements to Korean translations. (markt)
      + Add: Improvements to Chinese translations. (markt)
      + Add: Improvements to Japanese translations by tak7iji. (markt)

Tenable has extracted the preceding description block directly from the SUSE security advisory.

Note that Nessus has not tested for these issues but has instead relied only on the application's self-reported version
number.");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1233435");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1234663");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1234664");
  script_set_attribute(attribute:"see_also", value:"https://bugzilla.suse.com/1236809");
  # https://lists.suse.com/pipermail/sle-security-updates/2025-January/020069.html
  script_set_attribute(attribute:"see_also", value:"http://www.nessus.org/u?8ea84f84");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2024-50379");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2024-52317");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2024-54677");
  script_set_attribute(attribute:"see_also", value:"https://www.suse.com/security/cve/CVE-2024-56337");
  script_set_attribute(attribute:"solution", value:
"Update the affected packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:C/I:C/A:C");
  script_set_cvss_temporal_vector("CVSS2#E:POC/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:P/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2024-54677");
  script_set_attribute(attribute:"cvss3_score_source", value:"CVE-2024-56337");

  script_set_attribute(attribute:"exploitability_ease", value:"Exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"true");

  script_set_attribute(attribute:"vuln_publication_date", value:"2024/10/09");
  script_set_attribute(attribute:"patch_publication_date", value:"2025/01/07");
  script_set_attribute(attribute:"plugin_publication_date", value:"2025/01/09");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10-admin-webapps");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10-el-5_0-api");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10-jsp-3_1-api");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10-lib");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10-servlet-6_0-api");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:tomcat10-webapps");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:suse_linux:15");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_set_attribute(attribute:"stig_severity", value:"I");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"SuSE Local Security Checks");

  script_copyright(english:"This script is Copyright (C) 2025 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/SuSE/release", "Host/SuSE/rpm-list");

  exit(0);
}


include('rpm.inc');

if (!get_kb_item('Host/local_checks_enabled')) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
var os_release = get_kb_item("Host/SuSE/release");
if (isnull(os_release) || os_release !~ "^(SLED|SLES|SUSE)") audit(AUDIT_OS_NOT, "SUSE / openSUSE");
var os_ver = pregmatch(pattern: "^(SLE(S|D)(?:_SAP)?\d+|SUSE([\d.]+))", string:os_release);
if (isnull(os_ver)) audit(AUDIT_UNKNOWN_APP_VER, 'SUSE / openSUSE');
os_ver = os_ver[1];
if (! preg(pattern:"^(SLES15|SLES_SAP15|SUSE15\.6)$", string:os_ver)) audit(AUDIT_OS_NOT, 'SUSE SLES15 / SLES_SAP15 / openSUSE 15', 'SUSE / openSUSE (' + os_ver + ')');

if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

var cpu = get_kb_item('Host/cpu');
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ('x86_64' >!< cpu && cpu !~ "^i[3-6]86$" && 's390' >!< cpu && 'aarch64' >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, 'SUSE / openSUSE (' + os_ver + ')', cpu);

var service_pack = get_kb_item("Host/SuSE/patchlevel");
if (isnull(service_pack)) service_pack = "0";
if (os_ver == "SLES15" && (! preg(pattern:"^(5|6)$", string:service_pack))) audit(AUDIT_OS_NOT, "SLES15 SP5/6", os_ver + " SP" + service_pack);
if (os_ver == "SLES_SAP15" && (! preg(pattern:"^(5|6)$", string:service_pack))) audit(AUDIT_OS_NOT, "SLES_SAP15 SP5/6", os_ver + " SP" + service_pack);

var pkgs = [
    {'reference':'tomcat10-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-admin-webapps-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-el-5_0-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-jsp-3_1-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-lib-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-servlet-6_0-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-webapps-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.5']},
    {'reference':'tomcat10-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-admin-webapps-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-el-5_0-api-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-jsp-3_1-api-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-lib-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-servlet-6_0-api-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-webapps-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES_SAP15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLES_SAP-release-15.6']},
    {'reference':'tomcat10-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-admin-webapps-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-el-5_0-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-jsp-3_1-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-lib-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-servlet-6_0-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-webapps-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-ESPOS-release-5']},
    {'reference':'tomcat10-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-admin-webapps-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-el-5_0-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-jsp-3_1-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-lib-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-servlet-6_0-api-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-webapps-10.1.34-150200.5.31.1', 'sp':'5', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-LTSS-release-15.5', 'sles-ltss-release-15.5']},
    {'reference':'tomcat10-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-admin-webapps-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-el-5_0-api-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-jsp-3_1-api-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-lib-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-servlet-6_0-api-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-webapps-10.1.34-150200.5.31.1', 'sp':'6', 'release':'SLES15', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['SLE_HPC-release-15.6', 'sle-module-web-scripting-release-15.6', 'sles-release-15.6']},
    {'reference':'tomcat10-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-admin-webapps-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-doc-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-docs-webapp-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-el-5_0-api-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-embed-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-jsp-3_1-api-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-jsvc-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-lib-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-servlet-6_0-api-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']},
    {'reference':'tomcat10-webapps-10.1.34-150200.5.31.1', 'release':'SUSE15.6', 'rpm_spec_vers_cmp':TRUE, 'exists_check':['openSUSE-release-15.6']}
];

var ltss_caveat_required = FALSE;
var flag = 0;
foreach var package_array ( pkgs ) {
  var reference = NULL;
  var _release = NULL;
  var sp = NULL;
  var _cpu = NULL;
  var exists_check = NULL;
  var rpm_spec_vers_cmp = NULL;
  if (!empty_or_null(package_array['reference'])) reference = package_array['reference'];
  if (!empty_or_null(package_array['release'])) _release = package_array['release'];
  if (!empty_or_null(package_array['sp'])) sp = package_array['sp'];
  if (!empty_or_null(package_array['cpu'])) _cpu = package_array['cpu'];
  if (!empty_or_null(package_array['exists_check'])) exists_check = package_array['exists_check'];
  if (!empty_or_null(package_array['rpm_spec_vers_cmp'])) rpm_spec_vers_cmp = package_array['rpm_spec_vers_cmp'];
  if (reference && _release) {
    if (exists_check) {
      var check_flag = 0;
      foreach var check (exists_check) {
        if (!rpm_exists(release:_release, rpm:check)) continue;
        if ('ltss' >< tolower(check)) ltss_caveat_required = TRUE;
        check_flag++;
      }
      if (!check_flag) continue;
    }
    if (rpm_check(release:_release, sp:sp, cpu:_cpu, reference:reference, rpm_spec_vers_cmp:rpm_spec_vers_cmp)) flag++;
  }
}

if (flag)
{
  var ltss_plugin_caveat = NULL;
  if(ltss_caveat_required) ltss_plugin_caveat = '\n' +
    'NOTE: This vulnerability check contains fixes that apply to\n' +
    'packages only available in SUSE Enterprise Linux Server LTSS\n' +
    'repositories. Access to these package security updates require\n' +
    'a paid SUSE LTSS subscription.\n';
  security_report_v4(
      port       : 0,
      severity   : SECURITY_HOLE,
      extra      : rpm_report_get() + ltss_plugin_caveat
  );
  exit(0);
}
else
{
  var tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, 'tomcat10 / tomcat10-admin-webapps / tomcat10-doc / etc');
}
