#%NASL_MIN_LEVEL 80900
##
# (C) Tenable, Inc.
##

include('compat.inc');

if (description)
{
  script_id(226428);
  script_version("1.1");
  script_set_attribute(attribute:"plugin_modification_date", value:"2025/03/05");

  script_cve_id("CVE-2023-40030");

  script_name(english:"Linux Distros Unpatched Vulnerability : CVE-2023-40030");

  script_set_attribute(attribute:"synopsis", value:
"The Linux/Unix host has one or more packages installed with a vulnerability that the vendor indicates will not be
patched.");
  script_set_attribute(attribute:"description", value:
"The Linux/Unix host has one or more packages installed that are impacted by a vulnerability without a vendor supplied
patch available.

  - Cargo downloads a Rust project's dependencies and compiles the project. Starting in Rust 1.60.0 and prior
    to 1.72, Cargo did not escape Cargo feature names when including them in the report generated by `cargo
    build --timings`. A malicious package included as a dependency may inject nearly arbitrary HTML here,
    potentially leading to cross-site scripting if the report is subsequently uploaded somewhere. The
    vulnerability affects users relying on dependencies from git, local paths, or alternative registries.
    Users who solely depend on crates.io are unaffected. Rust 1.60.0 introduced `cargo build --timings`, which
    produces a report of how long the different steps of the build process took. It includes lists of Cargo
    features for each crate. Prior to Rust 1.72, Cargo feature names were allowed to contain almost any
    characters (with some exceptions as used by the feature syntax), but it would produce a future
    incompatibility warning about them since Rust 1.49. crates.io is far more stringent about what it
    considers a valid feature name and has not allowed such feature names. As the feature names were included
    unescaped in the timings report, they could be used to inject Javascript into the page, for example with a
    feature name like `features = [<img src='' onerror=alert(0)]`. If this report were subsequently uploaded
    to a domain that uses credentials, the injected Javascript could access resources from the website
    visitor. This issue was fixed in Rust 1.72 by turning the future incompatibility warning into an error.
    Users should still exercise care in which package they download, by only including trusted dependencies in
    their projects. Please note that even with these vulnerabilities fixed, by design Cargo allows arbitrary
    code execution at build time thanks to build scripts and procedural macros: a malicious dependency will be
    able to cause damage regardless of these vulnerabilities. crates.io has server-side checks preventing this
    attack, and there are no packages on crates.io exploiting these vulnerabilities. crates.io users still
    need to excercise care in choosing their dependencies though, as remote code execution is allowed by
    design there as well. (CVE-2023-40030)

Note that Nessus relies on the presence of the package as reported by the vendor.");
  script_set_attribute(attribute:"solution", value:
"There is no known solution at this time.");
  script_set_attribute(attribute:"agent", value:"unix");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:P/I:P/A:N");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N");
  script_set_cvss3_temporal_vector("CVSS:3.0/E:U/RL:O/RC:C");
  script_set_attribute(attribute:"cvss_score_source", value:"CVE-2023-40030");

  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");
  script_set_attribute(attribute:"vendor_unpatched", value:"true");

  script_set_attribute(attribute:"vuln_publication_date", value:"2023/08/24");
  script_set_attribute(attribute:"plugin_publication_date", value:"2025/03/05");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"generated_plugin", value:"current");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_family(english:"Misc.");

  script_copyright(english:"This script is Copyright (C) 2025 and is owned by Tenable, Inc. or an Affiliate thereof.");

  script_dependencies("ssh_get_info2.nasl");
  script_require_keys("Host/cpu", "Host/local_checks_enabled", "global_settings/vendor_unpatched");
  script_require_ports("Host/Debian/dpkg-l", "Host/Debian/release");

  exit(0);
}
include('vdf.inc');

# @tvdl-content
var vuln_data = {
 "metadata": {
  "spec_version": "1.0p"
 },
 "requires": [
  {
   "scope": "scan_config",
   "match": {
    "vendor_unpatched": true
   }
  },
  {
   "scope": "target",
   "match": {
    "os": "linux"
   }
  }
 ],
 "report": {
  "report_type": "unpatched"
 },
 "checks": [
  {
   "product": {
    "name": [
     "cargo",
     "cargo-doc",
     "librust-cargo-dev"
    ],
    "type": "dpkg_package"
   },
   "check_algorithm": "dpkg",
   "constraints": [
    {
     "requires": [
      {
       "scope": "target",
       "match": {
        "distro": "debian"
       }
      },
      {
       "scope": "target",
       "match": {
        "os_version": "12"
       }
      }
     ]
    }
   ]
  },
  {
   "product": {
    "name": [
     "cargo",
     "cargo-doc",
     "librust-cargo+openssl-dev",
     "librust-cargo-dev"
    ],
    "type": "dpkg_package"
   },
   "check_algorithm": "dpkg",
   "constraints": [
    {
     "requires": [
      {
       "scope": "target",
       "match": {
        "distro": "debian"
       }
      },
      {
       "scope": "target",
       "match": {
        "os_version": "11"
       }
      }
     ]
    }
   ]
  }
 ]
};

var vdf_res = vdf::check_and_report(vuln_data:vuln_data, severity:SECURITY_WARNING);
vdf::handle_check_and_report_errors(vdf_result: vdf_res);
